In [21]:
#1-12. 프로젝트 (2) load_wine : 와인을 분류해 봅시다
'''
1. 데이터셋의 구성을 파악하고, 데이터를 이해하는 과정이 포함되어있는가?
   1) 파악 : In 19
      - Number of Instances: 178 = 59 + 71 + 48
        . Class Distribution: class_0 (59), class_1 (71), class_2 (48) 구성됨 
      - Number of Attributes: 13개 특성치로 구성
      - Missing Attribute Values: 결측치 없음

    2) DATA INFO.: 
      - 학습data : Feature data(In 7,In 11) :178행이 13개로 구성 
                     >>> 형상정보(In 11) , 13개의 Feature name(In 14)
      - 정답data :  Label Data(In 8)        :    

      - 정답이름 : Target Names(In 9)       : array(['class_0', 'class_1', 'class_2'], dtype='<U7')
      - 객체(In 16)
      
2. 5가지 모델을 이용하여 학습을 수행하고 결과값을 얻었는가?
    * Precision: (정답율)예측된 true 전체(tp+fp) 중 true 비율(tp) , 모델에서 정답율  , 틀렸는데 맞다고 예측하면 안됨
   * recall    : (재현율)실제 true 자료(tp+fn) 중 true 비율(tp)   , 현실과 맞는 정답율,  맞았는데 틀렸다고 예측하면 안됨
   * f1-score  : (조화평균)정밀도 및 호출의 가중 평균      
   * macro avg : 평균
   * weighed avg : support * 각 결과 반영한 평균  
                                     accuracy     Precision      recall           f1-score
   1) Decision Tree 사용  : In 22      94 우수     96 우수       94 우수          95(weighed avg =94)  우수
   2) Random Forest 사용  : In  2     100 우수    100 우수      100 우수         100(weighed avg =100) 우수
   3) SVM 사용            : In  3      61 미흡     59 저조       61 미흡          56(weighed avg =54)  저조
   4) SGD Classifier 사용 : In  4      61 미흡     64 미흡       68 미흡          62(weighed avg =61)  미흡
   5) Logistic Regression : In  5      97 우수     98 우수       95 우수          96(weighed avg =97)  우수 
      중지:총 반복 횟수 한계 도달
   * 우수 : 100-90 , 양호 : 90 - 80 , 보통 : 80 - 70 , 미흡 : 70 - 60 , 저조 : 60 ~    

3. 모델의 평가 지표를 선택하고, 그 이유를 근거를 바탕으로 서술하였는가?

   결론 : 와인 구별은 분류알고리즘을 활용하는 것이 좋습니다.
          1) 이 모델은 Precision이 중요하다고 판단되며,(맞았다고 했는데 맞은 것의 비율,fp(맞다고 했는데 틀린 비율)가 
              적어지면 적을 수록 유리)해야 하고 recall보다 우선시 되어야(틀렸다고 했는데 맞는 문자임) 한다고 생각합니다.
          2) 지표상 Random Forest 알고리즘이 우수하며, 분류 알고리즘에도 적합하다고 판단되어 2)번 알고리즘을 이용하여 
             모델을 생성하는 것이 좋다고 생각됩니다.
 
'''

In [ ]:
#1-12. 프로젝트 (2) load_wine : 와인을 분류해 봅시다
# (1) 필요한 모듈 import
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# (2) 데이터 준비
wine = load_wine()
wine_data = wine.data
wine_label = wine.target

# (3) train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data, 
                                                    wine_label, 
                                                    test_size=0.2, 
                                                    random_state=7)

# (4) 모델 학습 및 예측
decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)

print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
accuracy

In [2]:
#Random Forest 사용해 보기
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        12

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [3]:
#SVM 사용해 보기
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

#모델 가져오기
svm_model = svm.SVC()

svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86         7
           1       0.58      0.88      0.70        17
           2       0.33      0.08      0.13        12

    accuracy                           0.61        36
   macro avg       0.59      0.61      0.56        36
weighted avg       0.55      0.61      0.54        36



In [4]:
#from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import SGDClassifier

#모델 가져오기
sgd_model = SGDClassifier()

sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.54      1.00      0.70         7
           1       0.89      0.47      0.62        17
           2       0.50      0.58      0.54        12

    accuracy                           0.61        36
   macro avg       0.64      0.68      0.62        36
weighted avg       0.69      0.61      0.61        36



In [5]:
#Logistic Regression 사용해 보기
from sklearn.linear_model import LogisticRegression

#모델 가져오기
logistic_model = LogisticRegression()

logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.94      1.00      0.97        17
           2       1.00      1.00      1.00        12

    accuracy                           0.97        36
   macro avg       0.98      0.95      0.96        36
weighted avg       0.97      0.97      0.97        36



/opt/conda/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
# Decision Tree 모델을 학습시키고, 정확도를 확인
# (1) 필요한 모듈 import
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# (2) 데이터 준비
wine = load_wine()

#(3) 데이터 이해하기
print(dir(wine))

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']


In [7]:
#Feature Data 지정하기
wine_data = wine.data
wine_data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [8]:
#Label Data 지정하기
wine_label = wine.target
wine_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [9]:
#Target Names 출력해 보기
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [10]:
#iris = load_digits()
print(dir(wine))

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']


In [11]:
#형상정보
print(wine_data.shape) 

(178, 13)


In [12]:
#샘플로 하나의 데이터만 확인
wine_data[0]

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])

In [13]:
#Target
print(wine_label.shape)
wine_label

(178,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [14]:
# 13개의 각 feature
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [15]:
# (4) train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data, 
                                                    wine_label, 
                                                    test_size=0.2, 
                                                    random_state=7)

In [19]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1