In [ ]:
#8-2. 배열은 가까이에~ 기본 통계 데이터를 계산해 볼까? (1) 평균 계산하기
total = 0
count = 0
numbers = input("Enter a number :  (<Enter Key> to quit)")
while numbers != "":
    try:
        x = float(numbers)
        count += 1
        total = total + x
    except ValueError:
        print('NOT a number! Ignored..')
    numbers = input("Enter a number :  (<Enter Key> to quit)")
avg = total / count
print("\n average is", avg)

In [1]:
#평균,편차
def numbers():
    X=[]
    while True:
        number = input("Enter a number (<Enter key> to quit)") 
        while number !="":
            try:
                x = float(number)
                X.append(x)
            except ValueError:
                print('>>> NOT a number! Ignored..')
            number = input("Enter a number (<Enter key> to quit)")
        if len(X) > 1:
            return X

def median(nums): 
    nums.sort()
    size = len(nums)
    p = size // 2
    if size % 2 == 0:
        pr = p
        pl = p-1
        mid = float((nums[pl]+nums[pr])/2)
    else:
        mid = nums[p]
    return mid

def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total = total + nums[i]
    return total / len(nums)

def std_dev(nums, avg):
    texp = 0.0
    for i in range(len(nums)):
        texp = texp + (nums[i] - avg) ** 2
    return (texp/len(nums)) ** 0.5
def main():
    X = numbers()
    med = median(X)
    avg = means(X)
    std = std_dev(X, avg)
    print("당신이 입력한 숫자{}의 ".format(X))
    print("중앙값은{}, 평균은{}, 표준편차는{}입니다.".format(med, avg, std))

if __name__ == '__main__':
    main()

Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)8
Enter a number (<Enter key> to quit)9
Enter a number (<Enter key> to quit)
당신이 입력한 숫자[5.0, 8.0, 9.0]의 
중앙값은8.0, 평균은7.333333333333333, 표준편차는1.699673171197595입니다.


In [2]:
#8-4. 끝판왕 등장! NumPy로 이 모든 걸 한방에! (1) NumPy 소개
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print("--------------------------")
print(B)
print(type(B))
print("--------------------------")
print(C)
print(type(C))
print("--------------------------")
print(D)
print(type(D))

#2) 크기 (size, shape, ndim) 
#ndarray.size
#ndarray.shape
#ndarray.ndim
#reshape()
A = np.arange(10).reshape(2, 5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.
print("행렬의 모양:", A.shape)
print("행렬의 축 개수:", A.ndim)
print("행렬 내 원소의 개수:", A.size)

[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>
행렬의 모양: (2, 5)
행렬의 축 개수: 2
행렬 내 원소의 개수: 10


In [3]:
A= np.arange(6).reshape(2, 3)
print(A)
print(A.dtype)
print(type(A))
print("-------------------------")

B = np.array([0, 1, 2, 3, 4, 5])  
print(B)
print(B.dtype)
print(type(B))
print("-------------------------")

C = np.array([0, 1, 2, 3, '4', 5])
print(C)
print(C.dtype)
print(type(C))
print("-------------------------")

D = np.array([0, 1, 2, 3, [4, 5], 6],dtype=object)  # 이런 ndarray도 만들어질까요?
print(D)
print(D.dtype)
print(type(D))

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>
-------------------------
[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>
-------------------------
['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>
-------------------------
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


In [ ]:
# 단위행렬
np.eye(3)
# 0 행렬
np.zeros([2,3])
# 1행렬
np.ones([3,3])

In [ ]:
# 3 X 3 행렬의 첫번째 행을 구해 봅시다. 
A = np.arange(9).reshape(3,3)
print("A:", A)
B = A[0]
print("B:", B)

# 0, 1을 인덱싱 하면 A의 첫번째 행에서 두번째 값을 참조합니다.
# 아래 두 결과는 정확히 같습니다.
print(A[0, 1])
print(B[1])

# 슬라이싱도 비슷합니다.
A[:-1]

In [6]:
# 이 슬라이싱의 결과는 
print(A[:,2:])
print("--------------")
print(A[:,1:])
print("--------------")
print(A[:,:])
print("--------------")
# 이 슬라이싱의 결과와 동일합니다.
print(A[:,-1:])
print("--------------")
print(A[:,-2:])
print("--------------")
print(A[:,-3:])

# 위 그림과 비교해서 이해해 보세요.

[[2]
 [5]]
--------------
[[1 2]
 [4 5]]
--------------
[[0 1 2]
 [3 4 5]]
--------------
[[2]
 [5]]
--------------
[[1 2]
 [4 5]]
--------------
[[0 1 2]
 [3 4 5]]


In [8]:
A = np.arange(9).reshape(3,3)
A[1,:2]
A[:2, 1:]
A[:,-1]

array([2, 5, 8])

In [11]:
#7) random
#NumPy에서도 다양한 의사 난수를 지원합니다.#
#앞으로 많이 쓰일 기능이니 익혀두세요. 아래는 주로 많이 쓰이는 것들이지만,
#np.random 패키지 안에는 이보다 훨씬 많은 기능이 내장되어 있습니다.
'''
np.random.randint()
np.random.choice()
np.random.permutation()
np.random.normal()
np.random.uniform()
'''
# 의사 난수를 생성하는 예제입니다. 여러번 실행해 보세요.

print(np.random.random())   # 0에서 1사이의 실수형 난수 하나를 생성합니다. 

print(np.random.randint(0,10))   # 0~9 사이 1개 정수형 난수 하나를 생성합니다. 

print(np.random.choice([0,1,2,3,4,5,6,7,8,9]))   # 리스트에 주어진 값 중 하나를 랜덤하게 골라줍니다.



0.02710081949633525
1
5


In [12]:
# 무작위로 섞인 배열을 만들어 줍니다. 
# 아래 2가지는 기능면에서 동일합니다. 

print(np.random.permutation(10))   
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))

[8 5 0 7 9 3 4 2 6 1]
[1 3 5 4 9 7 0 8 2 6]


In [13]:
# 아래 기능들은 어떤 분포를 따르는 변수를 임의로 표본추출해 줍니다. 

# 이것은 정규분포를 따릅니다.
print(np.random.normal(loc=0, scale=1, size=5))    # 평균(loc), 표준편차(scale), 추출개수(size)를 조절해 보세요.

# 이것은 균등분포를 따릅니다. 
print(np.random.uniform(low=-1, high=1, size=5))  # 최소(low), 최대(high), 추출개수(size)를 조절해 보세요.

[ 1.42416495  0.59268589  1.64425972  0.77595074 -0.43309891]
[ 0.19390275  0.72167389  0.2281375  -0.39681052 -0.49473391]


In [14]:
#8) 전치행렬
#arr.T: 행렬의 행과 열 맞바꾸기
#np.transpose: 축을 기준으로 행렬의 행과 열 바꾸기
A = np.arange(24).reshape(2,3,4)
print("A:", A)               # A는 (2,3,4)의 shape를 가진 행렬입니다. 
print("A의 전치행렬:", A.T)            
print("A의 전치행렬의 shape:", A.T.shape) # A의 전치행렬은 (4,3,2)의 shape를 가진 행렬입니다.


A: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
A의 전치행렬: [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
A의 전치행렬의 shape: (4, 3, 2)


In [15]:
# np.transpose는 행렬의 축을 어떻게 변환해 줄지 임의로 지정해 줄 수 있는 일반적인 행렬 전치 함수입니다. 
# np.transpose(A, (2,1,0)) 은 A.T와 정확히 같습니다.

B = np.transpose(A, (2,0,1))
print("A:", A)             # A는 (2,3,4)의 shape를 가진 행렬입니다. 
print("B:", B)             # B는 A의 3, 1, 2번째 축을 자신의 1, 2, 3번째 축으로 가진 행렬입니다.
print("B.shape:", B.shape)  # B는 (4,2,3)의 shape를 가진 행렬입니다.

A: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
B.shape: (4, 2, 3)


In [ ]:
#8-6. 끝판왕 등장! NumPy로 이 모든 걸 한방에! (3) NumPy로 기본 통계 데이터 계산해 보기
import numpy as np

def numbers():
    X = []
    number = input("Enter a number (<Enter key> to quit)") 
    # 하지만 2개 이상의 숫자를 받아야 한다는 제약조건을 제외하였습니다.
    while number != "":
        try:
            x = float(number)
            X.append(x)
        except ValueError:
            print('>>> NOT a number! Ignored..')
        number = input("Enter a number (<Enter key> to quit)")
    return X

def main():
    nums = numbers()       # 이것은 파이썬 리스트입니다. 
    num = np.array(nums)   # 리스트를 Numpy ndarray로 변환합니다.
    print("합", num.sum())
    print("평균값",num.mean())
    print("표준편차",num.std())
    print("중앙값",np.median(num))   # num.median() 이 아님에 유의해 주세요.

main()

In [ ]:
#8-8. 데이터의 행렬 변환 (2) 이미지의 행렬 변환
import matplotlib as mpl
import PIL

print( f'# matplotlib: {mpl.__version__}' )  
print(f'# PIL:  {PIL.__version__}')

In [16]:
'''이미지 조작에 쓰이는 메서드

open : Image.open()
size : Image.size
filename : Image.filename
crop : Image.crop((x0, y0, xt, yt))
resize : Image.resize((w,h))
save : Image.save()
'''
from PIL import Image, ImageColor
import os
img_path = os.getenv("HOME") + "/aiffel/data_represent/image/newyork.jpg"
img = Image.open(img_path)
print(img_path)
print(type(img))
img

img.size

W, H = img.size
print((W, H))

print(img.format)
print(img.size)
print(img.mode)

/aiffel/aiffel/data_represent/image/newyork.jpg
<class 'PIL.JpegImagePlugin.JpegImageFile'>
(212, 300)
JPEG
(212, 300)
RGB


In [19]:
#자르기
img.crop((30,30,100,100))
#저장
# 새로운 이미지 파일명
cropped_img_path = os.getenv("HOME") + "/aiffel/data_represent/image/cropped_img.jpg"
img.crop((30,30,100,100)).save(cropped_img_path)
print("저장 완료!")

!ls ~/aiffel/data_represent/image/cropped_img.jpg

import numpy as np
img_arr = np.array(img)
print(type(img))
print(type(img_arr))
print(img_arr.shape)
print(img_arr.ndim)

저장 완료!
/aiffel/aiffel/data_represent/image/cropped_img.jpg
<class 'PIL.JpegImagePlugin.JpegImageFile'>
<class 'numpy.ndarray'>
(300, 212, 3)
3


In [20]:
#확인
img_arr

array([[[133, 180, 250],
        [133, 180, 250],
        [133, 180, 250],
        ...,
        [133, 180, 250],
        [133, 180, 250],
        [133, 180, 250]],

       [[133, 180, 250],
        [133, 180, 250],
        [133, 180, 250],
        ...,
        [133, 180, 250],
        [133, 180, 250],
        [133, 180, 250]],

       [[133, 180, 250],
        [133, 180, 250],
        [133, 180, 250],
        ...,
        [133, 180, 250],
        [133, 180, 250],
        [133, 180, 250]],

       ...,

       [[164, 199, 255],
        [164, 199, 255],
        [164, 199, 255],
        ...,
        [164, 199, 255],
        [164, 199, 255],
        [164, 199, 255]],

       [[164, 199, 255],
        [164, 199, 255],
        [164, 199, 255],
        ...,
        [164, 199, 255],
        [164, 199, 255],
        [164, 199, 255]],

       [[164, 199, 255],
        [164, 199, 255],
        [164, 199, 255],
        ...,
        [164, 199, 255],
        [164, 199, 255],
        [164, 199, 255]]

In [29]:
#흑백
img_g_arr = np.array(img_g)
print(type(img_g_arr))
print(img_g_arr.shape)
print(img_g_arr.ndim)

img_g = Image.open(img_path).convert('L')

img_g_arr

<class 'numpy.ndarray'>
(300, 212)
2


array([[174, 174, 174, ..., 174, 174, 174],
       [174, 174, 174, ..., 174, 174, 174],
       [174, 174, 174, ..., 174, 174, 174],
       ...,
       [195, 195, 195, ..., 195, 195, 195],
       [195, 195, 195, ..., 195, 195, 195],
       [195, 195, 195, ..., 195, 195, 195]], dtype=uint8)

In [30]:
# color
red = ImageColor.getcolor('RED','RGB')
reda = ImageColor.getcolor('red','RGBA')
yellow = ImageColor.getcolor('yellow','RGB')
print(red)
print(reda)
print(yellow)

(255, 0, 0)
(255, 0, 0, 255)
(255, 255, 0)


In [ ]:
#구조화 data
# 파이썬 dict 로 표현한 전화번호부입니다. 
Country_PhoneNumber = {'Korea': 82, 'America': 1, 'Swiss': 41, 'Italy': 39, 'Japan': 81, 'China': 86, 'Rusia': 7}
Country_PhoneNumber['Korea']  # 키를 가지고 값을 조회할 수 있습니다.

In [31]:
#보물박스
treasure_box = {'rope':2, 
                'apple':10, 
                'torch': 6, 
                'gold coin': 50, 
                'knife': 1, 
                'arrow': 30}

def display_stuff(treasure_box):
    print("Congraturation!! you got a treasure box")
    for k, v in treasure_box.items():
        print("you have {} {}pcs".format(k, v))
display_stuff(treasure_box)

Congraturation!! you got a treasure box
you have rope 2pcs
you have apple 10pcs
you have torch 6pcs
you have gold coin 50pcs
you have knife 1pcs
you have arrow 30pcs


In [32]:
#은화 교환
coin_per_treasure = {'rope':1,
        'apple':2,
        'torch': 2,
        'gold coin': 5, 
        'knife': 30,
        'arrow': 1}

def total_silver(treasure_box, coin_per_treasure):
    total_coin = 0
    for treasure in treasure_box:
        coin = coin_per_treasure[treasure] * treasure_box[treasure]
        print("{} : {}coins/pcs * {}pcs = {} coins".format(
          treasure, coin_per_treasure[treasure], treasure_box[treasure], coin))
        total_coin += coin
    print('total_coin : ', total_coin)
total_silver(treasure_box, coin_per_treasure)

rope : 1coins/pcs * 2pcs = 2 coins
apple : 2coins/pcs * 10pcs = 20 coins
torch : 2coins/pcs * 6pcs = 12 coins
gold coin : 5coins/pcs * 50pcs = 250 coins
knife : 30coins/pcs * 1pcs = 30 coins
arrow : 1coins/pcs * 30pcs = 30 coins
total_coin :  344


In [33]:
#결과
treasure_box = {'rope': {'coin': 1, 'pcs': 2},
                'apple': {'coin': 2, 'pcs': 10},
                'torch': {'coin': 2, 'pcs': 6},
                'gold coin': {'coin': 5, 'pcs': 50},
                'knife': {'coin': 30, 'pcs': 1},
               	'arrow': {'coin': 1, 'pcs': 30}
               }
treasure_box['rope']

{'coin': 1, 'pcs': 2}

In [35]:
#series
import pandas as pd
ser = pd.Series(['a','b','c',3])
ser


array(['a', 'b', 'c', 3], dtype=object)

In [36]:
##series 통제
ser.values



RangeIndex(start=0, stop=4, step=1)

In [37]:
##series 통제


ser.index

RangeIndex(start=0, stop=4, step=1)

In [38]:
#시리즈 인자 교체
ser2 = pd.Series(['a', 'b', 'c', 3], index=['i','j','k','h'])
ser2

i    a
j    b
k    c
h    3
dtype: object

In [39]:
# 시리즈 할당 
ser2.index = ['Jhon', 'Steve', 'Jack', 'Bob']
ser2

Jhon     a
Steve    b
Jack     c
Bob      3
dtype: object

In [40]:
#index 표시
ser2.index

Index(['Jhon', 'Steve', 'Jack', 'Bob'], dtype='object')

In [41]:
#country
Country_PhoneNumber = {'Korea': 82, 'America': 1, 'Swiss': 41, 'Italy': 39, 'Japan': 81, 'China': 86, 'Rusia': 7}
ser3 = pd.Series(Country_PhoneNumber)
ser3

Korea      82
America     1
Swiss      41
Italy      39
Japan      81
China      86
Rusia       7
dtype: int64

In [42]:
ser3['Korea']

82

In [43]:
ser3['Italy':]

Italy    39
Japan    81
China    86
Rusia     7
dtype: int64

In [44]:
ser3.name = 'Country_PhoneNumber'
ser3.index.name = 'Country_Name'
ser3

Country_Name
Korea      82
America     1
Swiss      41
Italy      39
Japan      81
China      86
Rusia       7
Name: Country_PhoneNumber, dtype: int64

In [45]:
#시리즈
ser3.name = 'Country_PhoneNumber'
ser3.index.name = 'Country_Name'
ser3

Country_Name
Korea      82
America     1
Swiss      41
Italy      39
Japan      81
China      86
Rusia       7
Name: Country_PhoneNumber, dtype: int64

In [47]:
#data frame
data = {'Region' : ['Korea', 'America', 'Chaina', 'Canada', 'Italy'],
        'Sales' : [300, 200, 500, 150, 50],
        'Amount' : [90, 80, 100, 30, 10],
        'Employee' : [20, 10, 30, 5, 3]
        }
s = pd.Series(data)
s

d = pd.DataFrame(data)
d

Region  Sales  Amount  Employee
0    Korea    300      90        20
1  America    200      80        10
2   Chaina    500     100        30
3   Canada    150      30         5
4    Italy     50      10         3

In [48]:
d.columns

Index(['Region', 'Sales', 'Amount', 'Employee'], dtype='object')

In [49]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [50]:
d.index=['one','two','three','four','five']
d.columns = ['a','b','c','d']
d

a    b    c   d
one      Korea  300   90  20
two    America  200   80  10
three   Chaina  500  100  30
four    Canada  150   30   5
five     Italy   50   10   3

In [51]:
#csv
import pandas as pd
import os

csv_path = os.getenv("HOME") + "/aiffel/data_represent/data/covid19_italy_region.csv"
data = pd.read_csv(csv_path)
type(data)

pandas.core.frame.DataFrame

In [52]:
data


SNo                 Date Country  RegionCode     RegionName   Latitude  \
0      0  2020-02-24T18:00:00     ITA          13        Abruzzo  42.351222   
1      1  2020-02-24T18:00:00     ITA          17     Basilicata  40.639471   
2      2  2020-02-24T18:00:00     ITA           4   P.A. Bolzano  46.499335   
3      3  2020-02-24T18:00:00     ITA          18       Calabria  38.905976   
4      4  2020-02-24T18:00:00     ITA          15       Campania  40.839566   
..   ...                  ...     ...         ...            ...        ...   
793  793  2020-04-01T17:00:00     ITA           9        Toscana  43.769231   
794  794  2020-04-01T17:00:00     ITA           4    P.A. Trento  46.068935   
795  795  2020-04-01T17:00:00     ITA          10         Umbria  43.106758   
796  796  2020-04-01T17:00:00     ITA           2  Valle d'Aosta  45.737503   
797  797  2020-04-01T17:00:00     ITA           5         Veneto  45.434905   

     Longitude  HospitalizedPatients  IntensiveCarePatients  \
0    13.398438                     0                      0   
1    15.805148                     0                      0   
2    11.356624                     0                      0   
3    16.594402                     0                      0   
4    14.250850                     0                      0   
..         ...                   ...                    ...   
793  11.255889                  1120                    297   
794  11.121231                   345                     76   
795  12.388247                   173                     45   
796   7.320149                    85                     27   
797  12.338452                  1718                    350   

     TotalHospitalizedPatients  HomeConfinement  CurrentPositiveCases  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   
..                         ...              ...                   ...   
793                       1417             3015                  4432   
794                        421             1062                  1483   
795                        218              646                   864   
796                        112              428                   540   
797                       2068             6156                  8224   

     NewPositiveCases  Recovered  Deaths  TotalPositiveCases  TestsPerformed  
0                   0          0       0                   0               5  
1                   0          0       0                   0               0  
2                   0          0       0                   0               1  
3                   0          0       0                   0               1  
4                   0          0       0                   0              10  
..                ...        ...     ...                 ...             ...  
793               259        182     253                4867           36575  
794               124        214     173                1870            7675  
795                17        194      37                1095            9080  
796                 3         32      59                 631            1717  
797               470        902     499                9625          112746  

[798 rows x 17 columns]

In [53]:
data.head()

SNo                 Date Country  RegionCode    RegionName   Latitude  \
0    0  2020-02-24T18:00:00     ITA          13       Abruzzo  42.351222   
1    1  2020-02-24T18:00:00     ITA          17    Basilicata  40.639471   
2    2  2020-02-24T18:00:00     ITA           4  P.A. Bolzano  46.499335   
3    3  2020-02-24T18:00:00     ITA          18      Calabria  38.905976   
4    4  2020-02-24T18:00:00     ITA          15      Campania  40.839566   

   Longitude  HospitalizedPatients  IntensiveCarePatients  \
0  13.398438                     0                      0   
1  15.805148                     0                      0   
2  11.356624                     0                      0   
3  16.594402                     0                      0   
4  14.250850                     0                      0   

   TotalHospitalizedPatients  HomeConfinement  CurrentPositiveCases  \
0                          0                0                     0   
1                          0                0                     0   
2                          0                0                     0   
3                          0                0                     0   
4                          0                0                     0   

   NewPositiveCases  Recovered  Deaths  TotalPositiveCases  TestsPerformed  
0                 0          0       0                   0               5  
1                 0          0       0                   0               0  
2                 0          0       0                   0               1  
3                 0          0       0                   0               1  
4                 0          0       0                   0              10

In [54]:
data.tail()


SNo                 Date Country  RegionCode     RegionName   Latitude  \
793  793  2020-04-01T17:00:00     ITA           9        Toscana  43.769231   
794  794  2020-04-01T17:00:00     ITA           4    P.A. Trento  46.068935   
795  795  2020-04-01T17:00:00     ITA          10         Umbria  43.106758   
796  796  2020-04-01T17:00:00     ITA           2  Valle d'Aosta  45.737503   
797  797  2020-04-01T17:00:00     ITA           5         Veneto  45.434905   

     Longitude  HospitalizedPatients  IntensiveCarePatients  \
793  11.255889                  1120                    297   
794  11.121231                   345                     76   
795  12.388247                   173                     45   
796   7.320149                    85                     27   
797  12.338452                  1718                    350   

     TotalHospitalizedPatients  HomeConfinement  CurrentPositiveCases  \
793                       1417             3015                  4432   
794                        421             1062                  1483   
795                        218              646                   864   
796                        112              428                   540   
797                       2068             6156                  8224   

     NewPositiveCases  Recovered  Deaths  TotalPositiveCases  TestsPerformed  
793               259        182     253                4867           36575  
794               124        214     173                1870            7675  
795                17        194      37                1095            9080  
796                 3         32      59                 631            1717  
797               470        902     499                9625          112746

In [55]:
data.columns

Index(['SNo', 'Date', 'Country', 'RegionCode', 'RegionName', 'Latitude',
       'Longitude', 'HospitalizedPatients', 'IntensiveCarePatients',
       'TotalHospitalizedPatients', 'HomeConfinement', 'CurrentPositiveCases',
       'NewPositiveCases', 'Recovered', 'Deaths', 'TotalPositiveCases',
       'TestsPerformed'],
      dtype='object')

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   SNo                        798 non-null    int64  
 1   Date                       798 non-null    object 
 2   Country                    798 non-null    object 
 3   RegionCode                 798 non-null    int64  
 4   RegionName                 798 non-null    object 
 5   Latitude                   798 non-null    float64
 6   Longitude                  798 non-null    float64
 7   HospitalizedPatients       798 non-null    int64  
 8   IntensiveCarePatients      798 non-null    int64  
 9   TotalHospitalizedPatients  798 non-null    int64  
 10  HomeConfinement            798 non-null    int64  
 11  CurrentPositiveCases       798 non-null    int64  
 12  NewPositiveCases           798 non-null    int64  
 13  Recovered                  798 non-null    int64  

In [57]:
data.describe()

SNo  RegionCode    Latitude   Longitude  HospitalizedPatients  \
count  798.00000  798.000000  798.000000  798.000000            798.000000   
mean   398.50000   10.190476   43.046293   12.225955            533.058897   
std    230.50705    5.798698    2.490342    2.660615           1532.090841   
min      0.00000    1.000000   38.115697    7.320149              0.000000   
25%    199.25000    5.000000   41.125596   11.121231              5.000000   
50%    398.50000   10.000000   43.616760   12.388247             64.000000   
75%    597.75000   15.000000   45.434905   13.768136            325.750000   
max    797.00000   20.000000   46.499335   16.867367          11927.000000   

       IntensiveCarePatients  TotalHospitalizedPatients  HomeConfinement  \
count             798.000000                 798.000000       798.000000   
mean               82.596491                 615.655388       674.998747   
std               190.735985                1719.508711      1627.086600   
min                 0.000000                   0.000000         0.000000   
25%                 0.000000                   6.000000         8.000000   
50%                16.000000                  80.500000       109.000000   
75%                71.750000                 396.250000       552.750000   
max              1342.000000               13269.000000     12496.000000   

       CurrentPositiveCases  NewPositiveCases     Recovered       Deaths  \
count            798.000000        798.000000    798.000000   798.000000   
mean            1290.654135        138.553885    205.706767   162.677945   
std             3282.834715        327.616052   1060.433732   700.264327   
min                0.000000        -17.000000      0.000000     0.000000   
25%               14.250000          2.000000      0.000000     0.000000   
50%              205.000000         32.000000      3.000000     6.000000   
75%              998.750000        117.750000     34.000000    55.750000   
max            25765.000000       3251.000000  11415.000000  7593.000000   

       TotalPositiveCases  TestsPerformed  
count          798.000000      798.000000  
mean          1659.038847     7932.164160  
std           4945.629053    17067.087279  
min              0.000000        0.000000  
25%             14.250000      230.000000  
50%            210.500000     1610.000000  
75%           1110.750000     7493.000000  
max          44773.000000   121449.000000

In [58]:
data.isnull().sum()

SNo                          0
Date                         0
Country                      0
RegionCode                   0
RegionName                   0
Latitude                     0
Longitude                    0
HospitalizedPatients         0
IntensiveCarePatients        0
TotalHospitalizedPatients    0
HomeConfinement              0
CurrentPositiveCases         0
NewPositiveCases             0
Recovered                    0
Deaths                       0
TotalPositiveCases           0
TestsPerformed               0
dtype: int64

In [59]:
#EDA - 통계
data['RegionName'].value_counts()

Abruzzo                  38
Molise                   38
Valle d'Aosta            38
Umbria                   38
P.A. Trento              38
Toscana                  38
Sicilia                  38
Sardegna                 38
Puglia                   38
Piemonte                 38
Marche                   38
Basilicata               38
Lombardia                38
Liguria                  38
Lazio                    38
Friuli Venezia Giulia    38
Emilia-Romagna           38
Campania                 38
Calabria                 38
P.A. Bolzano             38
Veneto                   38
Name: RegionName, dtype: int64

In [60]:
data['RegionName'].value_counts()

Abruzzo                  38
Molise                   38
Valle d'Aosta            38
Umbria                   38
P.A. Trento              38
Toscana                  38
Sicilia                  38
Sardegna                 38
Puglia                   38
Piemonte                 38
Marche                   38
Basilicata               38
Lombardia                38
Liguria                  38
Lazio                    38
Friuli Venezia Giulia    38
Emilia-Romagna           38
Campania                 38
Calabria                 38
P.A. Bolzano             38
Veneto                   38
Name: RegionName, dtype: int64

In [61]:
data['Country'].value_counts()

ITA    798
Name: Country, dtype: int64

In [62]:
data['RegionName'].value_counts().sum()

798

In [63]:
data['Country'].value_counts().sum()

798

In [64]:
print("총 감염자", data['TotalPositiveCases'].sum())
print("전체 검사자 수", data['TestsPerformed'].sum())
print("사망자 수", data['Deaths'].sum())
print("회복자 수", data['Recovered'].sum())

총 감염자 1323913
전체 검사자 수 6329867
사망자 수 129817
회복자 수 164154


In [65]:
data.sum()

SNo                                                                     318003
Date                         2020-02-24T18:00:002020-02-24T18:00:002020-02-...
Country                      ITAITAITAITAITAITAITAITAITAITAITAITAITAITAITAI...
RegionCode                                                                8132
RegionName                   AbruzzoBasilicataP.A. BolzanoCalabriaCampaniaE...
Latitude                                                          34350.941591
Longitude                                                          9756.312476
HospitalizedPatients                                                    425381
IntensiveCarePatients                                                    65912
TotalHospitalizedPatients                                               491293
HomeConfinement                                                         538649
CurrentPositiveCases                                                   1029942
NewPositiveCases                                    

In [66]:
data.drop(['Latitude','Longitude','Country','Date','HospitalizedPatients',  'IntensiveCarePatients', 'TotalHospitalizedPatients','HomeConfinement','RegionCode','SNo'], axis=1, inplace=True)

data.corr()

CurrentPositiveCases  NewPositiveCases  Recovered  \
CurrentPositiveCases              1.000000          0.892083   0.903833   
NewPositiveCases                  0.892083          1.000000   0.760710   
Recovered                         0.903833          0.760710   1.000000   
Deaths                            0.937337          0.775184   0.986324   
TotalPositiveCases                0.990303          0.865022   0.954026   
TestsPerformed                    0.886860          0.755386   0.741827   

                        Deaths  TotalPositiveCases  TestsPerformed  
CurrentPositiveCases  0.937337            0.990303        0.886860  
NewPositiveCases      0.775184            0.865022        0.755386  
Recovered             0.986324            0.954026        0.741827  
Deaths                1.000000            0.975269        0.761221  
TotalPositiveCases    0.975269            1.000000        0.855529  
TestsPerformed        0.761221            0.855529        1.000000

In [ ]:
'''pandas 통계 관련 메서드
이상으로 pandas에서 제공하는 통계 관련 메서드를 정리했으니 한번 확인해 보세요.

count(): NA를 제외한 수를 반환합니다.
describe(): 요약 통계를 계산합니다.
min(), max(): 최소, 최댓값을 계산합니다.
sum(): 합을 계산합니다.
mean(): 평균을 계산합니다.
median(): 중앙값을 계산합니다.
var(): 분산을 계산합니다.
std(): 표준편차를 계산합니다.
argmin(), argmax(): 최소, 최댓값을 가지고 있는 값을 반환합니다.
idxmin(), idxmax(): 최소, 최댓값을 가지고 있는 인덱스를 반환합니다.
cumsum(): 누적 합을 계산합니다.
'''